### ISSUE TITLE
As a user, I can easily navigate around the app

### ISSUE THREAD

**Issue by EmilyScripts** [fac-14/Brickworks-Tollington_Project#16]

**Comment by MissArray** [comment]
Issues #16 and #17 could be merged?

**Comment by EmilyScripts** [comment]
I don't think these should be merged as #17 is referring to the menu specifically, such as they take you to the correct page and they are named appropriately as that is currently not the case in our prototype so this needs to be addressed. This issue means that if you use the back button on a page, it takes you logically back to the last page you were on.
