### ISSUE TITLE
Set up testing

### ISSUE THREAD

**Issue by EmilyScripts** [fac-14/Brickworks-Tollington_Project#28]

**Comment by MissArray** [comment]
**Add _codecov_ script**
Do we need to add 
`"report-coverage": "codecov" `
to the package.json? Currently there seems to be no script for _codecov_.

**Path pattern error when testing with _jest_.**
I've created a testing branch (**Octopus_testing**) and added two basic tests; however, the tests don't pass. Error message:
` testMatch: **/__tests__/**/*.js?(x),**/?(*.)+(spec|test).js?(x) - 0 matches
  testPathIgnorePatterns: /node_modules/ - 36 matches`

I tried replacing 
	`"test": "jest",`
with
	`"test": "jest src/tests --coverage",`
in the package.json to specify test path, but it made no difference. Any ideas?
