### ISSUE TITLE
Need to know average amount of events that are currently held in the area

### ISSUE THREAD

**Issue by EmilyScripts** [fac-14/Brickworks-Tollington_Project#29]

**Comment by MissArray** [comment]
Varies, depending on the project:
1. The '[Power to Change](http://www.octopuscommunities.org.uk/our-projects/power-to-change/)' project has zero published events.
2. The 'Inspiring Communities' project [()](http://www.octopuscommunities.org.uk/our-projects/inspiring-community-centres/) had about 30 events in July, but all were part of a special events-week.
3. The 'Communities Hubs' project [()](http://www.octopuscommunities.org.uk/our-projects/community-hubs/) also has zero published events.
