### ISSUE TITLE
Server stuff (Code Review)

### ISSUE THREAD

**Issue by jamiecoe** [fac-14/Brickworks-Tollington_Project#77]
### Separating routes from `server.js`

Currently, `server.js` contains your express setup & middleware, your route definitions and the command to start the server listening. As your app grows, this file could quickly get too big so I would suggest moving routes to a separate file. You could also make use of the [Express Router](https://expressjs.com/en/api.html#express.router) object, which allows you to modularise and easily mount a set of routes on a specific paths. For example:

Create a new file - `apiRoutes.js`
```js
const apiRoutes = require('express').Router();

apiRoutes.post('/create-event', (req, res) => {
   // create-event stuff
})

apiRoutes.post('/getAllEvents', (req, res) => {
   // getAllEvents stuff
})

// all your api other routes

module.export = apiRoutes;
```

Then in `server.js`
```js
const apiRoutes = require('./apiRoutes')

// all requests which begin with /api will go through to apiRoutes
app.use('/api', apiRoutes); 
```

### Serving up the front-end for non-homepage urls
Try going directly to one of your page sections, without navigating there from the home page. Eg:
https://vigorous-swirles-227d32.netlify.com/categories

Are you seeing a Page Not Found message? This is because currently you are only serving up your `/dist` folder for [calls to your home route](https://github.com/fac-14/Brickworks-Tollington_Project/blob/02b5235d978cc6c910233e7441c193fdd6e0ba03/src/server.js#L8). You can fix this by adding the following route (**Important:** this must come AFTER all your other route definitions):

```js
app.get('*', (req, res) => {
 res.sendFile(path.join(__dirname, '..', 'dist', 'index.html'));
});
``` 
This will serve your front end code for any requests that aren't to your `/api/...` routes. From here, `react-router` will use the url to render the correct components.

**Comment by harryyy27** [comment]
does 
```
app.get('*', (req, res) => {
 res.sendFile(path.join(__dirname, '..', 'dist', 'index.html'));
});
```
come before the error routes?

**Comment by jamiecoe** [comment]
Yes it does, although it actually makes your 404 route redundant, as you will always serve your front-end code. You will now need to handle 404 routes with `react-router`. Your `express` 500 route is still needed though 👍

**Comment by harryyy27** [comment]
Okay cool! The 404 route is handled in react-router already. Gonna need to have a little think about how we can trigger the 500 error.

**Comment by harryyy27** [comment]
I'm guessing that changing the filename isn't an option for client projects ahah

**Comment by jamiecoe** [comment]
You could have a `<Route path ='/server-error' component = {ServerError} />`, where `ServerError` is a component that renders a message telling users there's been a problem with the server.

Then when you get a 500 response from your server, you can use `this.props.history.push('/server-error');` to redirect the user. 

We did something similar in one of our [FAC projects](https://github.com/fac-12/peppr/blob/master/client/src/components/App.js).

**Comment by harryyy27** [comment]
Hi not really sure why but my server isn't working with this new set up?

**Comment by harryyy27** [comment]
I have 2 files, apiroutes and server.js?

**Comment by jamiecoe** [comment]
@harryyy27
Can you post the code of how you've got it setup? Or do you have the new setup on a branch you could push up?

**Comment by harryyy27** [comment]
It's okay, i modularised it in a more basic way and had server,js, app.js and router.js
