### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by EmilyScripts** [fac-14/Brickworks-Tollington_Project#89]
Link is currently broken and am not sure what this page is supposed to be as it's currently trying to link to a pdf

**Comment by MissArray** [comment]
@EmilyScripts The `pages` branch I originally made locally contained the file `assets`, which contains the PDF and is there in the `Styling` branch. However, it looks like merging with master before pushing my pages branch deleted that folder. I'm pushing the same branch again, with the `assets` folder and making a PR again.

**Comment by MissArray** [comment]
Replaced url,  seems to work.
